# frozen_string_literal: true

require "fileutils"

namespace :flat_pack do
  desc "Prepare FlatPack stylesheets and gem @source paths for the host app Tailwind build"
  task prepare_tailwind_assets: :environment do
    prepare_flat_pack_stylesheets
    mirror_gem_tailwind_sources
    write_gem_tailwind_sources
  end

  def prepare_flat_pack_stylesheets
    return unless defined?(FlatPack::Engine)

    source_dir = FlatPack::Engine.root.join("app/assets/stylesheets/flat_pack")
    target_dir = Rails.root.join("app/assets/tailwind/flat_pack")

    FileUtils.mkdir_p(target_dir)

    %w[variables.css rich_text.css content_editor.css].each do |filename|
      FileUtils.cp(source_dir.join(filename), target_dir.join(filename))
    end

    application_css = source_dir.join("application.css").read
                        .gsub('"flat_pack/variables.css"', '"./variables.css"')
                        .gsub('"flat_pack/rich_text.css"', '"./rich_text.css"')
                        .gsub('"flat_pack/content_editor.css"', '"./content_editor.css"')

    target_dir.join("application.css").write(application_css)
  end

  # Copy (not symlink) gem trees into a path inside the host app. Tailwind does not
  # follow symlinks for @source, and absolute Engine roots vary by Bundler layout.
  def mirror_gem_tailwind_sources
    mirror_root = Rails.root.join("tmp/tailwind_scan")
    FileUtils.rm_rf(mirror_root)
    FileUtils.mkdir_p(mirror_root)

    gem_tailwind_source_targets.each do |name, path|
      next unless path&.exist?

      destination = mirror_root.join(name)
      FileUtils.mkdir_p(destination.dirname)
      FileUtils.cp_r(path, destination)
    end
  end

  # Absolute Engine.root paths remain as a fallback when the mirror is empty.
  def write_gem_tailwind_sources
    mirrored = Rails.root.join("tmp/tailwind_scan")
    sources = []

    if mirrored.exist?
      sources << %(@source "#{mirrored}";)
      sources << %(@source "#{mirrored}/**/*.{rb,erb}";)
    end

    gem_tailwind_source_paths.each do |path|
      sources << %(@source "#{path}";)
      sources << %(@source "#{path}/**/*.{rb,erb}";)
    end

    # FlatPack::Grid builds responsive column classes dynamically; keep them safelisted.
    sources << <<~CSS.strip
      @source inline("grid grid-cols-1 grid-cols-2 grid-cols-3 grid-cols-4 grid-cols-6 grid-cols-12 sm:grid-cols-2 md:grid-cols-2 md:grid-cols-3 md:grid-cols-4 md:grid-cols-6 lg:grid-cols-2 lg:grid-cols-3 lg:grid-cols-4 lg:grid-cols-6 lg:grid-cols-12 xl:grid-cols-4 gap-2 gap-4 gap-6 items-start items-center items-stretch w-5 h-5");
    CSS

    content = <<~CSS
      /* Generated by flat_pack:prepare_tailwind_assets — do not edit by hand. */
      #{sources.join("\n")}
    CSS

    Rails.root.join("app/assets/tailwind/gem_sources.css").write(content)
  end

  def gem_tailwind_source_targets
    {
      "flat_pack_components" => (FlatPack::Engine.root.join("app/components") if defined?(FlatPack::Engine)),
      "recording_studio_admin_views" => (RecordingStudioAdmin::Engine.root.join("app/views") if defined?(RecordingStudioAdmin::Engine)),
      "recording_studio_admin_lib" => (RecordingStudioAdmin::Engine.root.join("lib") if defined?(RecordingStudioAdmin::Engine)),
      "recording_studio_views" => (RecordingStudio::Engine.root.join("app/views") if defined?(RecordingStudio::Engine)),
      "recording_studio_accessible_views" => (RecordingStudioAccessible::Engine.root.join("app/views") if defined?(RecordingStudioAccessible::Engine)),
      "recording_studio_root_switchable_views" => (RecordingStudioRootSwitchable::Engine.root.join("app/views") if defined?(RecordingStudioRootSwitchable::Engine)),
      "recording_studio_api_views" => (RecordingStudioApi::Engine.root.join("app/views") if defined?(RecordingStudioApi::Engine)),
      "recording_studio_api_lib" => (RecordingStudioApi::Engine.root.join("lib") if defined?(RecordingStudioApi::Engine))
    }
  end

  def gem_tailwind_source_paths
    gem_tailwind_source_targets.values.compact.select(&:exist?).map { |path| path.expand_path.to_s }
  end
end

%w[tailwindcss:build tailwindcss:watch].each do |task_name|
  next unless Rake::Task.task_defined?(task_name)

  Rake::Task[task_name].enhance(["flat_pack:prepare_tailwind_assets"])
end
