# frozen_string_literal: true

require "rails/generators"

module RecordingStudioApi
  module Generators
    class InstallGenerator < Rails::Generators::Base
      source_root File.expand_path("templates", __dir__)

      desc "Installs RecordingStudioApi engine into your application"

      class_option(
        :mount_path,
        type: :string,
        default: "/recording_studio_api",
        desc: "Route prefix used when mounting the engine"
      )

      def mount_engine
        route %(mount RecordingStudioApi::Engine, at: "#{options[:mount_path]}")
      end

      def copy_initializer
        template "recording_studio_api_initializer.rb", "config/initializers/recording_studio_api.rb"
      end

      def add_yaml_config
        return unless yes?("Would you like to add `config/recording_studio_api.yml` for environment-specific settings? [y/N]")

        template "recording_studio_api.yml", "config/recording_studio_api.yml"
      end

      def add_tailwind_source
        tailwind_css_path = Rails.root.join("app/assets/tailwind/application.css")
        return show_missing_tailwind_notice unless File.exist?(tailwind_css_path)

        copy_tailwind_prepare_rake_task
        ensure_gem_sources_import(tailwind_css_path)

        tailwind_content = File.read(tailwind_css_path)
        missing_lines = missing_tailwind_source_lines(tailwind_content)

        if missing_lines.empty?
          say "Tailwind already configured to include RecordingStudioApi and FlatPack sources.", :green
          return
        end

        if tailwind_content.include?('@import "tailwindcss"')
          inject_tailwind_sources(tailwind_css_path, missing_lines)
          return
        end

        show_manual_tailwind_notice(missing_lines)
      end

      def show_readme
        readme "INSTALL.md" if behavior == :invoke
      end

      private

      def copy_tailwind_prepare_rake_task
        copy_file(
          "flat_pack_tailwind_assets.rake",
          "lib/tasks/flat_pack_tailwind_assets.rake"
        )
      end

      def ensure_gem_sources_import(tailwind_css_path)
        content = File.read(tailwind_css_path)
        return if content.include?("gem_sources.css")

        inject_into_file tailwind_css_path, after: "@import \"tailwindcss\";\n" do
          <<~CSS

            /* Generated by flat_pack:prepare_tailwind_assets (mirrored Engine @source + Grid safelist). */
            @import "./gem_sources.css";
          CSS
        end
      rescue StandardError
        say "Could not add gem_sources.css import; add `@import \"./gem_sources.css\";` after tailwindcss.", :yellow
      end

      def show_missing_tailwind_notice
        say "Tailwind CSS not detected. Skipping Tailwind configuration.", :yellow
        say "If you use Tailwind, add these lines to your Tailwind CSS config:", :yellow
        tailwind_source_lines.each do |line|
          say "  #{line}", :yellow
        end
      end

      def missing_tailwind_source_lines(tailwind_content)
        tailwind_source_lines.reject { |line| tailwind_content.include?(line) }
      end

      def inject_tailwind_sources(tailwind_css_path, missing_lines)
        inject_into_file tailwind_css_path, after: "@import \"tailwindcss\";\n" do
          "#{formatted_tailwind_source_block(missing_lines)}\n"
        end
        say "Added RecordingStudioApi and FlatPack sources to Tailwind CSS configuration.", :green
        say "Run 'bin/rails flat_pack:prepare_tailwind_assets tailwindcss:build' to rebuild your CSS.", :green
      end

      def formatted_tailwind_source_block(missing_lines)
        engine_lines = missing_lines.select { |line| line.include?("recording_studio_api") }
        flat_pack_lines = missing_lines - engine_lines

        [
          "\n/* Include RecordingStudioApi engine views for Tailwind CSS */",
          engine_lines,
          "\n/* Include FlatPack component sources for Tailwind CSS */",
          flat_pack_lines,
          "\n/* Grid/icon utilities FlatPack builds dynamically */",
          '@source inline("grid grid-cols-1 grid-cols-2 grid-cols-3 grid-cols-4 grid-cols-6 grid-cols-12 sm:grid-cols-2 md:grid-cols-2 md:grid-cols-3 md:grid-cols-4 md:grid-cols-6 lg:grid-cols-2 lg:grid-cols-3 lg:grid-cols-4 lg:grid-cols-6 lg:grid-cols-12 xl:grid-cols-4 gap-2 gap-4 gap-6 items-start items-center items-stretch w-5 h-5");'
        ].flatten.reject(&:empty?).join("\n")
      end

      def show_manual_tailwind_notice(missing_lines)
        say "Could not find @import \"tailwindcss\" in your Tailwind config.", :yellow
        say "Please manually add these lines to your Tailwind CSS config:", :yellow
        missing_lines.each do |line|
          say "  #{line}", :yellow
        end
      end

      def tailwind_source_lines
        [
          '@source "../../vendor/bundle/**/recording_studio_api/app/views/**/*.erb";',
          '@source "../../../../../../usr/local/bundle/ruby/**/bundler/gems/' \
          'recording_studio_api-*/app/views/**/*.erb";',
          # GitHub gem checkout directory is flatpack-*; gem name is flat_pack.
          '@source "../../vendor/bundle/**/flatpack*/app/components/**/*.{rb,erb}";',
          '@source "../../vendor/bundle/**/flat_pack*/app/components/**/*.{rb,erb}";',
          '@source "../../../../../../usr/local/bundle/ruby/**/bundler/gems/' \
          'flatpack-*/app/components/**/*.{rb,erb}";',
          '@source "../../../../../../usr/local/bundle/ruby/**/bundler/gems/' \
          'flat_pack-*/app/components/**/*.{rb,erb}";',
          *resolved_flat_pack_source_lines
        ]
      end

      def resolved_flat_pack_source_lines
        return [] unless defined?(FlatPack::Engine)

        components = FlatPack::Engine.root.join("app/components")
        return [] unless components.exist?

        tailwind_css_path = Rails.root.join("app/assets/tailwind/application.css")
        relative = components.relative_path_from(tailwind_css_path.dirname)
        [%(@source "#{relative}";)]
      rescue StandardError
        []
      end
    end
  end
end
