require "fileutils"

namespace :flat_pack do
  desc "Prepare FlatPack stylesheets and gem @source paths for the dummy app Tailwind build"
  task prepare_tailwind_assets: :environment do
    prepare_flat_pack_stylesheets
    write_gem_tailwind_sources
  end

  def prepare_flat_pack_stylesheets
    return unless defined?(FlatPack::Engine)

    source_dir = FlatPack::Engine.root.join("app/assets/stylesheets/flat_pack")
    target_dir = Rails.root.join("app/assets/tailwind/flat_pack")

    FileUtils.mkdir_p(target_dir)

    %w[variables.css rich_text.css content_editor.css].each do |filename|
      FileUtils.cp(source_dir.join(filename), target_dir.join(filename))
    end

    application_css = source_dir.join("application.css").read
      .gsub('"flat_pack/variables.css"', '"./variables.css"')
      .gsub('"flat_pack/rich_text.css"', '"./rich_text.css"')
      .gsub('"flat_pack/content_editor.css"', '"./content_editor.css"')

    target_dir.join("application.css").write(application_css)
  end

  # Bundler may install git gems under rbenv, /usr/local/bundle, or vendor/bundle.
  # Write absolute @source paths at build time — Tailwind does not follow symlinks,
  # and relative vendor/bundle globs miss rbenv checkouts.
  def write_gem_tailwind_sources
    sources = gem_tailwind_source_paths.flat_map do |path|
      [
        %(@source "#{path}";),
        %(@source "#{path}/**/*.{rb,erb}";)
      ]
    end

    content = <<~CSS
      /* Generated by flat_pack:prepare_tailwind_assets — do not edit by hand. */
      #{sources.join("\n")}
    CSS

    Rails.root.join("app/assets/tailwind/gem_sources.css").write(content)
  end

  def gem_tailwind_source_paths
    [
      (FlatPack::Engine.root.join("app/components") if defined?(FlatPack::Engine)),
      (RecordingStudioAdmin::Engine.root.join("app/views") if defined?(RecordingStudioAdmin::Engine)),
      (RecordingStudioAdmin::Engine.root.join("lib") if defined?(RecordingStudioAdmin::Engine)),
      (RecordingStudio::Engine.root.join("app/views") if defined?(RecordingStudio::Engine)),
      (RecordingStudioAccessible::Engine.root.join("app/views") if defined?(RecordingStudioAccessible::Engine)),
      (RecordingStudioRootSwitchable::Engine.root.join("app/views") if defined?(RecordingStudioRootSwitchable::Engine))
    ].compact.select(&:exist?).map { |path| path.expand_path.to_s }
  end
end

%w[tailwindcss:build tailwindcss:watch].each do |task_name|
  next unless Rake::Task.task_defined?(task_name)

  Rake::Task[task_name].enhance(["flat_pack:prepare_tailwind_assets"])
end
